// Generated by CoffeeScript 1.12.7
'use strict';
app.directive('participantMetadataForm', [
  'constantService', 'messageService', function(constants, messages) {
    return {
      restrict: 'E',
      templateUrl: 'volume/participantmetadata.html',
      link: function($scope) {
        var form, volume;
        volume = $scope.volume;
        form = $scope.participantMetadataForm;
        
        form.save = function() {
          console.log(form.data.metadata[0]);
          var data;
          messages.clear(form);
          data = new FormData();
          data.append('metadata', form.data.metadata[0]);
          console.log(data);
          form.$setSubmitted();
          return volume.detectcsv(data).then(function() {
            form.validator.server({});
            messages.add({
              type: 'green',
              body: constants.message('volume.edit.success'),
              owner: form
            });
            form.$setPristine();
          }, function(res) {
            form.$setUnsubmitted();
            form.validator.server(res);
            messages.addError({
              body: constants.message('volume.edit.error'),
              report: res,
              owner: form
            });
          });
        };
      }
    };
  }
]);
