#!/usr/bin/env bash

set -euo pipefail 

rcvr=$1
RESULT="$(nix-build -A pkgs.databrary --show-trace)"
echo "building Databrary binaries..."
nix-copy-closure --to "$rcvr" "$RESULT"
echo "copy closure of Databrary binaries completed..."

ssh "$rcvr" bash -x <<EOF 
echo "Hello, Databrary is attempting to create a link to it's application executable found in the nix-store"
nix-env -i "$RESULT"
EOF
