#!/bin/sh -e
echo "========Cleaning up stale artifacts from prior build============================================"
cabal clean

echo "========Installing any new dependencies========================================================="
cabal install --only-dependencies --force-reinstalls

echo "========Build Setup script into dist/setup/setup==============================================="
echo "========Determine version from git commit======================================================"
echo "========Configuring build settings============================================================="
echo "========Download lastest node dependencies====================================================="
cabal configure --user

echo "========Build Setup script into dist/setup/setup==============================================="
echo "========Determine version from git commit======================================================"
echo "========Download lastest node dependencies====================================================="
echo "========Run any DB Migrations=================================================================="
echo "========Build into dist/build=================================================================="
echo "========Generate web assets===================================================================="
echo "========Set transcode scripts as executable===================================================="
echo "========Add version suffix to executable name=================================================="
cabal install
echo "========The prefix of this version will provide you with the version built: `git describe`====="

echo "========Build/Install sucessful.================================================================"
echo "========Run ~build/.cabal/bin/databrary-X.Y.Z.NN================================================"
echo "========Run from inside a directory containing databrary.conf (/home/databrary)================="
