#! /usr/bin/env bash

set -eu -o pipefail

dbName="databrary-nix-db"
./initializeDB.sh $dbName
sleep 5
socketPath=./$dbName/work/
if [ -d "$socketPath" ]; then
  echo "connection to postgres socket..."
  postgres -D $socketPath -E -k . -h "" &
fi 
# $(nix-build db.nix --no-out-link)

