#!/usr/bin/env bash
set -eu

# TODO: stop creating nix directory, just rely on standard nix install script, don't worry about ordering sudo operaions first
# perform sudo tasks first
if ! [ -e /nix ]; then
    echo "Creating /nix directory using sudo"
    sudo mkdir -m 0755 /nix
fi
echo "Changing owner of /nix to $USER using sudo"
sudo chown -R $USER:$USER /nix

echo "Manually running nix/install script, fixed to nix 2.0 currently"
# curl https://nixos.org/nix/install | sh
cd /tmp
curl -o install-2.0 https://raw.githubusercontent.com/NixOS/nixos-homepage/master/nix/install-2.0
chmod +x install-2.0
sh ./install-2.0
