#!/bin/sh -e
echo "========Cleaning up stale artifacts from prior build============================================"
cabal clean

echo "========Installing any new dependencies========================================================="
cabal install --only-dependencies --force-reinstalls

#setup=dist/setup/setup
#mkdir -p `dirname $setup`
#ghc -Wall -fwarn-tabs --make -odir dist/setup -hidir dist/setup -i. Setup.hs -o $setup
#[[ -z ${opt[f]+set} && -f dist/setup-config ]] || $setup configure --user -f ${opt[p]+-}devel
echo "========Build Setup script into dist/setup/setup==============================================="
echo "========Determine version from git commit======================================================"
echo "========Configuring build settings============================================================="
echo "========Download lastest node dependencies====================================================="
cabal configure --user

##$setup build ${opt[p]--j3}
#cabal build

echo "========Build Setup script into dist/setup/setup==============================================="
echo "========Download lastest node dependencies====================================================="
echo "========Run any DB Migrations=================================================================="
echo "========Build into dist/build=================================================================="
echo "========Generate web assets===================================================================="
echo "========Set transcode scripts as executable===================================================="
#if [[ -n ${opt[i]+set} ]] ; then
#	$setup install "$@"
#elif [[ -z ${opt[n]+set}${opt[p]+set} ]] ; then
#	echo "Starting databrary..."
#	databrary_datadir=. databrary_sysconfdir=. dist/build/databrary/databrary "$@"
#fi
cabal install
echo "========Add version suffix to executable name=================================================="
version=`cat databrary.cabal | grep -i "^version:" | tr '[:upper:]' '[:lower:]' | sed -E 's/version: *([0-9\.a-bA-Z0-9]*) */\1/'`
exedir=".cabal-sandbox/bin"
pushd $exedir
cp databrary databrary-$version
cp schemabrary schemabrary-$version
popd
echo "========The prefix of this version will provide you with the version built: `git describe`====="

echo "========Build/Install sucessful.================================================================"
echo "========Run ~build/.cabal/bin/databrary-X.Y.Z.NN================================================"
echo "========Run from inside a directory containing databrary.conf (/home/databrary)================="
