#!/usr/bin/env bash
set -Eeuo pipefail

#
# Loads the library in ghcid
#
# Just to keep things interesting, ghcid is run within nix-shell, which both
# makes sure ghcid is available, and makes sure cabal can access library
# dependencies.

nix-shell --option binary-caches "https://cache.nixos.org http://devdatabrary2.home.nyu.edu:5000" \
    --run 'ghcid -c "cabal repl --ghc-options=\"-Wno-deprecations -Wno-overlapping-patterns\" lib:databrary"'
