function initMap() {
  var map;
  var bounds = new google.maps.LatLngBounds();
  var mapOptions = {
      mapTypeId: 'roadmap'
  };
                  
  map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);

  //var geocoder = new google.maps.Geocoder();

  // var universities = [
  //   ["Aalto University"],
  //   ["Abertay University"],
  //   ["Abraham Baldwin Agricultural College"],
  //   ["Academia Sinica"],
  //   ["Academic Medical Center"],
  //   ["Adam Mickiewicz University"],
  //   ["Adelphi University"],
  //   ["Aix Marseille University"],
  //   ["Albert Einstein College of Medicine"],
  //   ["Albright College"],
  //   ["Alexandru Ioan Cuza University"],
  //   ["Amherst College"],
  //   ["Appalachian State University"],
  //   ["Aristotle University of Thessaloniki"],
  //   ["Arizona State University"],
  //   ["Association Italian Teachers Method Feldenkrais (AIIMF)"],
  //   ["Australian Catholic University"],
  //   ["Babes-Bolyai University"],
  //   ["Bahcesehir University (Bahçeşehir Üniversitesi)"],
  //   ["Banja Luka University"],
  //   ["Bard College"],
  //   ["Barnard College, Columbia University"],
  //   ["Baruch College, CUNY"],
  //   ["Baylor College of Medicine"],
  //   ["Bilkent University"],
  //   ["Binghamton University"],
  //   ["Birkbeck, University of London"],
  //   ["Bordeaux INP - ENSEIRB-MATMECA"],
  //   ["Borough of Manhattan Community College"],
  //   ["Boston Children's Hospital"],
  //   ["Boston College"],
  //   ["Boston Medical Center"],
  //   ["Boston University"],
  //   ["Brigham Young University"],
  //   ["Brooklyn College, CUNY"],
  //   ["Brown University"],
  //   ["Bucknell University"],
  //   ["California Polytechnic State University, San Luis Obispo"],
  //   ["California State Polytechnic University, Pomona"],
  //   ["California State University, Fullerton"],
  //   ["California State University, Long Beach"],
  //   ["California State University, Northridge"],
  //   ["California State University, Sacramento"],
  //   ["California State University, San Bernardino"],
  //   ["California State University, Stanislaus"],
  //   ["Canisius College"],
  //   ["Capella University"],
  //   ["Cardiff University"],
  //   ["Carleton University"],
  //   ["Carlos Albizu University, San Juan"],
  //   ["Carnegie Mellon University"],
  //   ["Catholic University of Portugal (Universidade Catolica Portuguesa)"],
  //   ["Central European University"],
  //   ["Charité - University Medicine Berlin"],
  //   ["Chatham University"],
  //   ["Children's Hospital of Philadelphia (CHOP)"],
  //   ["Children’s Mercy Kansas City"],
  //   ["Christopher Newport University"],
  //   ["Cincinnati Children's Hospital Medical Center"],
  //   ["Clark University"],
  //   ["Claude Bernard University Lyon 1"],
  //   ["Clemson University"],
  //   ["Colby College"],
  //   ["College of Staten Island, CUNY"],
  //   ["College of the Holy Cross"],
  //   ["College of William & Mary"],
  //   ["Colorado College"],
  //   ["Colorado State University"],
  //   ["Columbia University"],
  //   ["Concordia University"],
  //   ["Connecticut College"],
  //   ["Copenhagen Business School"],
  //   ["Cornell University"],
  //   ["Curtin University"],
  //   ["Dalhousie University"],
  //   ["Dartmouth University"],
  //   ["DAV College"],
  //   ["Davidson College"],
  //   ["Deakin University"],
  //   ["DePaul University"],
  //   ["Duke University"],
  //   ["Duquesne University"],
  //   ["Earlham College"],
  //   ["East Carolina University"],
  //   ["Eastern Michigan University"],
  //   ["East Tennessee State University"],
  //   ["Edogawa University"],
  //   ["Emory University"],
  //   ["Farmingdale State College"],
  //   ["Federal University of Alagoas"],
  //   ["Federal University of Pará"],
  //   ["Federal University of Rio Grande do Sul (Universidade Federal do Rio Grande do Sul)"],
  //   ["Federal University of Rio Grande North"],
  //   ["Florida International University"],
  //   ["Florida State University"],
  //   ["Foundation CTIC"],
  //   ["Franklin and Marshall College"],
  //   ["Free University of Berlin (Freie Universität)"],
  //   ["Gallaudet University"],
  //   ["Gangneung-Wonju National University"],
  //   ["General Hospital of Mexico"],
  //   ["George Mason University"],
  //   ["Georgetown University"],
  //   ["George Washington University"],
  //   ["Georgia Institute of Technology"],
  //   ["Georgia State University"],
  //   ["Gettysburg College"],
  //   ["Goethe-University"],
  //   ["Goldsmiths University of London"],
  //   ["Graduate Center, CUNY"],
  //   ["Grand Valley State University"],
  //   ["Grinnell College"],
  //   ["Gustavus Adolphus College"],
  //   ["Hangzhou Normal University"],
  //   ["Harvard University"],
  //   ["Hofstra University"],
  //   ["Hong Kong University of Science and Technology"],
  //   ["Humboldt State University"],
  //   ["Humboldt-University of Berlin"],
  //   ["Hunter College, CUNY"],
  //   ["IE University"],
  //   ["Illinois Institute of Technology"],
  //   ["Indiana University"],
  //   ["Indiana University Kokomo"],
  //   ["Indian Institute of Science"],
  //   ["Indraprastha Institute of Information Technology Delhi"],
  //   ["Infantium"],
  //   ["INSERM"],
  //   ["Institute of Business Administration, Karachi"],
  //   ["Institute of Psychology, Chinese Academy of Sciences"],
  //   ["Interdisciplinary Center Herzliya"],
  //   ["IRCCS Stella Maris Foundation"],
  //   ["ISCTE - University Institute of Lisbon (IUL)"],
  //   ["Isfahan University of Medical Sciences"],
  //   ["Istanbul Technical University"],
  //   ["Italian Hospital of Buenos Aires"],
  //   ["ITESO University (Instituto Tecnologico y de Estudios Superiores de Occidente)"],
  //   ["Jagiellonian University"],
  //   ["Japan Advanced Institute of Science and Technology"],
  //   ["Johns Hopkins University"],
  //   ["Kansas State University"],
  //   ["Keele University"],
  //   ["King Khalid University"],
  //   ["Kingston University London"],
  //   ["Kobe University"],
  //   ["Koc University"],
  //   ["Kumamoto University"],
  //   ["Kutztown University of Pennsylvania"],
  //   ["Kyoto University"],
  //   ["Kyushu University"],
  //   ["Laboratoire de Sciences Cognitives et Psycholinguistique"],
  //   ["Lafayette College"],
  //   ["Lancaster University"],
  //   ["Lehigh University"],
  //   ["Lehman College, CUNY"],
  //   ["Leiden University"],
  //   ["Leipzig University (Universität Leipzig)"],
  //   ["Liverpool Hope University"],
  //   ["Lock Haven University"],
  //   ["London School of Economics and Political Science"],
  //   ["London South Bank University"],
  //   ["Louisiana State University"],
  //   ["Loyola University Chicago"],
  //   ["Ludwig Maximilian University of Munich"],
  //   ["Lynchburg College"],
  //   ["Macquarie University"],
  //   ["Marshall University"],
  //   ["Massachusetts Institute of Technology"],
  //   ["Max Planck Institute for Evolutionary Anthropology"],
  //   ["Max Planck Institute for Human Development"],
  //   ["Max Planck Institute for Psycholinguistics"],
  //   ["McGill University"],
  //   ["McMaster University"],
  //   ["Memorial University"],
  //   ["Mercy College"],
  //   ["Metropolitan State University"],
  //   ["Miami University"],
  //   ["Michigan State University"],
  //   ["Michigan Technological University"],
  //   ["Middlesex University"],
  //   ["Millersville University"],
  //   ["Montana State University"],
  //   ["Montclair State University"],
  //   ["Mount Saint Mary's University"],
  //   ["Narsee Monjee Institute of Management Studies"],
  //   ["National Autonomous University of Mexico"],
  //   ["National Institute of Astrophysics, Optics and Electronics"],
  //   ["National Institute of Child Health & Human Development NICHD"],
  //   ["National Institute of Mental Health (NUDZ/ NIMH)"],
  //   ["National Institute of Technology Durgapur"],
  //   ["National Institute of Technology Rourkela"],
  //   ["National Science Foundation (NSF)"],
  //   ["National Scientific and Technical Research Council (CONICET)"],
  //   ["National Taipei University of Technology"],
  //   ["National University of Córdoba"],
  //   ["National University of La Plata"],
  //   ["National University of Singapore"],
  //   ["Nationwide Children's Hospital"],
  //   ["Nencki Institute of Experimental Biology, Polish Academy of Sciences"],
  //   ["Newcastle University"],
  //   ["New College of Florida"],
  //   ["New School for Social Research"],
  //   ["New York State Institute for Basic Research in Developmental Disabilities"],
  //   ["New York University, School of Medicine"],
  //   ["New York University (NYU)"],
  //   ["Niagara University"],
  //   ["Niigata University"],
  //   ["Nile University of Nigeria"],
  //   ["North Dakota State University"],
  //   ["Northeastern University"],
  //   ["Northern Illinois University"],
  //   ["Northwestern University"],
  //   ["Norwegian University of Science and Technology"],
  //   ["Oberlin College"],
  //   ["Ohio State University"],
  //   ["Ohio State University, Lima"],
  //   ["Okinawa Institute of Science and Technology"],
  //   ["Oklahoma State University"],
  //   ["Old Dominion University"],
  //   ["Omsk State Pedagogical University"],
  //   ["Oregon Health and Science University"],
  //   ["Oregon State University"],
  //   ["Osaka University"],
  //   ["Oxford Brookes University"],
  //   ["Ozyegin University"],
  //   ["Pace University"],
  //   ["Pakistan Institute of Learning and Living"],
  //   ["Paris Descartes University"],
  //   ["Peking University First Hopsital"],
  //   ["Penn State University, Abington"],
  //   ["Penn State University, Brandywine"],
  //   ["Penn State University, University Park"],
  //   ["Penn State University, Worthington-Scranton"],
  //   ["Pomona College"],
  //   ["Pontifical Catholic University of Rio Grande do Sul (PUCRS)"],
  //   ["Pontificia Universidad Católica de Chile"],
  //   ["Princeton University"],
  //   ["Providence College"],
  //   ["Punjab University"],
  //   ["Purdue University"],
  //   ["Queen's University"],
  //   ["Queen's University, Belfast"],
  //   ["Queens College, CUNY"],
  //   ["Radboud University"],
  //   ["Ramapo College"],
  //   ["Randolph-Macon College"],
  //   ["Rhodes College"],
  //   ["Rice University"],
  //   ["Rikkyo University"],
  //   ["Rochester Institute of Technology"],
  //   ["Roosevelt University"],
  //   ["Rosalind Franklin University of Medicine and Science"],
  //   ["Rutgers University, Newark"],
  //   ["Rutgers University, New Brunswick"],
  //   ["Ryerson University"],
  //   ["Saarland University"],
  //   ["Sabanci University"],
  //   ["Sacred Heart University"],
  //   ["Saint Joseph's University"],
  //   ["Sakushin Gakuin University"],
  //   ["Sam Houston State University"],
  //   ["San Diego State University"],
  //   ["San Francisco State University"],
  //   ["San Jose State University"],
  //   ["Santa Clara University"],
  //   ["Sapienza University of Rome"],
  //   ["Seoul National University"],
  //   ["Seton Hall University"],
  //   ["Simon Fraser University"],
  //   ["Singapore University of Technology and Design"],
  //   ["Skidmore College"],
  //   ["Slippery Rock University"],
  //   ["Smith-Kettlewell Eye Research Institute"],
  //   ["Southern Illinois University"],
  //   ["Southern New Hampshire University"],
  //   ["Southwestern University"],
  //   ["St. Francis Xavier University"],
  //   ["St. John's University"],
  //   ["St. Lawrence University"],
  //   ["St. Mary's College of Maryland"],
  //   ["Stanford University"],
  //   ["State University of New York at Fredonia"],
  //   ["Stockholm University"],
  //   ["Sun Yat-Sen University"],
  //   ["Swarthmore"],
  //   ["Swinburne University of Technology"],
  //   ["SWPS University of Social Sciences and Humanities"],
  //   ["Syracuse University"],
  //   ["Teachers College, Columbia University"],
  //   ["Technion – Israel Institute of Technology"],
  //   ["Teesside University"],
  //   ["Tel Aviv University"],
  //   ["Temple University"],
  //   ["Texas A&M University"],
  //   ["Texas Christian University"],
  //   ["Texas Woman's University"],
  //   ["The Catholic University of America"],
  //   ["The University of British Columbia"],
  //   ["The University of Newcastle"],
  //   ["The University of Queensland"],
  //   ["The University of Scranton"],
  //   ["The University of Sydney"],
  //   ["The University of Texas at Arlington"],
  //   ["The University of Texas at Austin"],
  //   ["The University of Texas at Dallas"],
  //   ["The University of Western Australia"],
  //   ["Thompson Rivers University"],
  //   ["Tokyo Metropolitan University"],
  //   ["Toulouse University"],
  //   ["Trent University"],
  //   ["Trinity College"],
  //   ["Trinity College Dublin"],
  //   ["Tufts University"],
  //   ["Tulane University"],
  //   ["Ulm University"],
  //   ["Ulster University"],
  //   ["Universidade Federal do Paraná"],
  //   ["Université du Québec à Trois-Rivières"],
  //   ["Université du Québec en Outaouais"],
  //   ["Université Libre de Bruxelles"],
  //   ["Université Paul-Valéry Montpellier 3"],
  //   ["Universiti Putra Malaysia"],
  //   ["University at Buffalo"],
  //   ["University College London"],
  //   ["University Duesseldorf (Heinrich-Heine-Universität Düsseldorf)"],
  //   ["University Ibn Zohr (Université Ibn Zohr)"],
  //   ["University of Akron"],
  //   ["University of Alberta"],
  //   ["University of Algarve"],
  //   ["University of Angers"],
  //   ["University of Arizona"],
  //   ["University of Arkansas"],
  //   ["University of Arkansas at Little Rock"],
  //   ["University of Auckland"],
  //   ["University of Bath"],
  //   ["University of Brazil (Universidade de Brasilia)"],
  //   ["University of Cagliari"],
  //   ["University of Calgary"],
  //   ["University of California, Berkeley"],
  //   ["University of California, Davis"],
  //   ["University of California, Irvine"],
  //   ["University of California, Los Angeles"],
  //   ["University of California, Merced"],
  //   ["University of California, Riverside"],
  //   ["University of California, San Diego"],
  //   ["University of California, San Francisco"],
  //   ["University of California, Santa Barbara"],
  //   ["University of California, Santa Cruz"],
  //   ["University of Cambridge"],
  //   ["University of Campinas"],
  //   ["University of Canterbury"],
  //   ["University of Central Florida"],
  //   ["University of Central Lancashire"],
  //   ["University of Chicago"],
  //   ["University of Cleveland"],
  //   ["University of Cologne"],
  //   ["University of Colorado, Boulder"],
  //   ["University of Colorado, Colorado Springs"],
  //   ["University of Connecticut"],
  //   ["University of Cyprus"],
  //   ["University of Delaware"],
  //   ["University of Denver"],
  //   ["University of East Anglia"],
  //   ["University of East London"],
  //   ["University of Erlangen-Nuremberg"],
  //   ["University of Florida"],
  //   ["University of Franche-Comté (Université de Franche-Comté)"],
  //   ["University of Geneva"],
  //   ["University of Georgia"],
  //   ["University of Giessen"],
  //   ["University of Gothenburg"],
  //   ["University of Gottingen (Georg-August-Universität Göttingen)"],
  //   ["University of Granada (Universidad de Granada)"],
  //   ["University of Greifswald (Ernst-Moritz-Arndt-Universität Greifswald)"],
  //   ["University of Haifa"],
  //   ["University of Hamburg (Universität Hamburg)"],
  //   ["University of Hartford"],
  //   ["University of Hawaii - Manoa"],
  //   ["University of Houston"],
  //   ["University of Hull"],
  //   ["University of Illinois at Chicago"],
  //   ["University of Illinois Urbana-Champaign"],
  //   ["University of Innsbruck (Universität Innsbruck)"],
  //   ["University of Iowa"],
  //   ["University of Kansas"],
  //   ["University of Kent"],
  //   ["University of Kentucky"],
  //   ["University of Konstanz (Universität Konstanz)"],
  //   ["University of Leeds"],
  //   ["University of Lille"],
  //   ["University of Lincoln"],
  //   ["University of Lisbon"],
  //   ["University of Liverpool"],
  //   ["University of Los Andes (Universidad de los Andes)"],
  //   ["University of Louisiana, Lafayette"],
  //   ["University of Louisville"],
  //   ["University of Malaya"],
  //   ["University of Manchester"],
  //   ["University of Manitoba"],
  //   ["University of Maryland"],
  //   ["University of Massachusetts, Amherst"],
  //   ["University of Massachusetts, Boston"],
  //   ["University of Massachusetts, Dartmouth"],
  //   ["University of Memphis"],
  //   ["University of Miami"],
  //   ["University of Michigan"],
  //   ["University of Minnesota"],
  //   ["University of Missouri"],
  //   ["University of Missouri, Kansas City"],
  //   ["University of Missouri, St. Louis"],
  //   ["University of Mons"],
  //   ["University of Montana"],
  //   ["University of Montreal (Université de Montréal)"],
  //   ["University of Muenster (Münster)"],
  //   ["University of Nantes"],
  //   ["University of Nebraska, Lincoln"],
  //   ["University of Nevada, Las Vegas"],
  //   ["University of New Hampshire"],
  //   ["University of New Mexico"],
  //   ["University of New South Wales"],
  //   ["University of Nicosia"],
  //   ["University of North Carolina, Asheville"],
  //   ["University of North Carolina, Chapel Hill"],
  //   ["University of North Carolina, Greensboro"],
  //   ["University of North Carolina, School of Medicine"],
  //   ["University of North Carolina, Wilmington"],
  //   ["University of North Florida"],
  //   ["University of North Georgia"],
  //   ["University of Notre Dame"],
  //   ["University of Oklahoma"],
  //   ["University of Oregon"],
  //   ["University of Oslo"],
  //   ["University of Otago"],
  //   ["University of Ottawa"],
  //   ["University of Padua (Università di Padova)"],
  //   ["University of Paris Nanterre"],
  //   ["University of Pennsylvania"],
  //   ["University of Pittsburgh"],
  //   ["University of Poitiers (Université de Poitiers)"],
  //   ["University of Portsmouth"],
  //   ["University of Puget Sound"],
  //   ["University of Reading"],
  //   ["University of Redlands"],
  //   ["University of Regina"],
  //   ["University of Rennes (Université de Rennes)"],
  //   ["University of Rochester"],
  //   ["University of Salford"],
  //   ["University of São Paulo"],
  //   ["University of Sheffield"],
  //   ["University of South Brittany (Université de Bretagne Sud)"],
  //   ["University of South Carolina"],
  //   ["University of South Dakota"],
  //   ["University of Southern California"],
  //   ["University of South Florida"],
  //   ["University of St Andrews"],
  //   ["University of Stirling"],
  //   ["University of Surrey"],
  //   ["University of Sussex"],
  //   ["University of Tampere"],
  //   ["University of Tennessee"],
  //   ["University of the Balearic Islands"],
  //   ["University of the Basque Country"],
  //   ["University of the Incarnate Word"],
  //   ["University of the Pacific"],
  //   ["University of the Republic"],
  //   ["University of the Sciences"],
  //   ["University of the West of England"],
  //   ["University of Toledo"],
  //   ["University of Toronto"],
  //   ["University of Toulouse - Jean Jaurès (Université Toulouse - Jean Jaurès)"],
  //   ["University of Trento"],
  //   ["University of Trier (Universität Trier)"],
  //   ["University of Tuebingen (Tübingen)"],
  //   ["University of Utah"],
  //   ["University of Verona"],
  //   ["University of Virginia"],
  //   ["University of Warsaw"],
  //   ["University of Washington"],
  //   ["University of Waterloo"],
  //   ["University of Western Sydney"],
  //   ["University of Wisconsin, Green Bay"],
  //   ["University of Wisconsin, Madison"],
  //   ["University of Wisconsin, Milwaukee"],
  //   ["University of Wisconsin, Oshkosh"],
  //   ["University of Wisconsin, Whitewater"],
  //   ["University of Wuerzburg (University of Würzburg )"],
  //   ["University of York"],
  //   ["University of Zurich (Universität Zürich)"],
  //   ["University Paris 8"],
  //   ["University Saint Anne (Université Sainte-Anne)"],
  //   ["Uppsala University"],
  //   ["Utrecht University"],
  //   ["Vanderbilt University"],
  //   ["Vietnam Maritime University"],
  //   ["Villanova University"],
  //   ["Virginia Commonwealth University"],
  //   ["Virginia Military Institute"],
  //   ["Virginia Tech"],
  //   ["Vrije Universiteit Brussel"],
  //   ["Wabash College"],
  //   ["Wake Forest University"],
  //   ["Washington State University"],
  //   ["Washington University, St Louis"],
  //   ["Wayne State University"],
  //   ["Weill Cornell Medical College"],
  //   ["Wellesley College"],
  //   ["Wesleyan University"],
  //   ["Westmont College"],
  //   ["West Virginia University"],
  //   ["Wheaton College"],
  //   ["Whitman College"],
  //   ["Widener University"],
  //   ["Wilfrid Laurier University"],
  //   ["Williams College"],
  //   ["Worcester Polytechnic Institute"],
  //   ["Xidian University"],
  //   ["Yale University"],
  //   ["York University"] 
  // ];

  // var markers = [];
  // var offset = 0;

  // if (geocoder) {
  //   $.each(universities.slice(510, 518), function(index, value){
  //     setTimeout(function(){
  //       geocoder.geocode({ 'address': value[0] }, function (results, status) {
  //         if (status == google.maps.GeocoderStatus.OK) {
  //           value.push(results[0].geometry.location.lat());
  //           value.push(results[0].geometry.location.lng());
  //           console.log(universities);
  //         }
  //         else {
  //           console.log(google.maps.GeocoderStatus);
  //         }
  //       });
  //     }, 500 + offset);
  //     offset += 500;
  //   });  
  // }

  // setTimeout(function(){
  //   console.log(universities);
  // }, 6000);

  var markers = [
    ["New York University", 40.72951339999999, -73.99646089999999, "collecting"],
    ["Georgetown University", 38.9076089, -77.07225849999998, "collecting"],
    ["Cornell University", 42.4534492, -76.47350269999998, "collecting"],
    ["Purdue University", 40.4237054, -86.92119459999998, "collecting"],
    ["Virginia Commonwealth University", 37.5488396, -77.45272720000003, "collecting"],
    ["University of Oregon", 44.0448302, -123.07260550000001, "collecting"],
    ["University of California at Riverside", 33.9737055, -117.32806440000002, "collecting"],
    ["Stanford University", 37.4274745, -122.16971899999999, "collecting"],
    ["Boston University", 42.3504997, -71.1053991, "collecting"],
    ["Penn State University", 40.7982133, -77.8599084, "collecting"],
    ["California State University at Long Beach", 33.7838235, -118.11409040000001, "collecting"],
    ["Ohio State University", 40.0141905, -83.0309143, "collecting"],
    ["University of Pittsburgh", 40.4443533, -79.96083499999997, "collecting"],
    ["CUNY -- College of Staten Island", 40.6018152, -74.14849040000001, "collecting"],
    ["California State University at Fullerton", 33.8829226, -117.88692609999998, "collecting"],
    ["Michigan State University", 42.701848, -84.48217190000003, "collecting"],
    ["University of Texas at Austin", 30.29128, -97.73858, "collecting"],
    ["Princeton University", 40.3439888, -74.65144809999998, "collecting"],
    ["Rutgers University", 40.741187, -74.17530950000003, "collecting"],
    ["Tulane University", 29.9403477, -90.12072790000002, "collecting"],
    ["University of Miami", 25.7904064, -80.21199279999996, "collecting"],
    ["Emory University", 33.7925195, -84.32399889999999, "collecting"],
    ["Vanderbilt University", 36.1447034, -86.80265509999998, "collecting"],
    ["University of California at Davis", 38.5382322, -121.76171249999999, "collecting"],
    ["Children's Hospital of Philadelphia", 39.9489145, -75.1939595, "collecting"],
    ["College of William & Mary", 37.271674, -76.71337799999998, "collecting"],
    ["University of California at Santa Cruz", 36.9914738, -122.05829719999997, "collecting"],
    ["University of California at Merced", 37.3648748, -120.42540020000001, "collecting"],
    ["University of Houston", 29.7199489, -95.3422334, "collecting"],
    ["Indiana University", 39.1745704, -86.51294580000001, "collecting"],
    ["University of Georgia", 33.9480053, -83.37732210000001, "collecting"],
    ["University of Chicago", 41.7886079, -87.59871329999999, "collecting"],
    ["Brown University", 41.8267718, -71.40254820000001, "noncollecting"],
    ["Penn State University", 40.7982133, -77.8599084, "noncollecting"],
    ["NICHD", 39.0292164, -77.13551009999998, "noncollecting"],
    ["Ryerson University", 43.6576585, -79.3788017, "noncollecting"],
    ["Arizona State University", 33.4242399, -111.92805269999997, "noncollecting"],
    ["Lehigh University", 40.6069087, -75.3782832, "noncollecting"],
    ["Texas A&M", 30.618531, -96.336499, "noncollecting"],
    ["Penn State University", 40.7982133, -77.8599084, "noncollecting"],
    ["Penn State University", 40.7982133, -77.8599084, "noncollecting"],
    ["University of California at Riverside", 33.9737055, -117.32806440000002, "noncollecting"],
    ["Cornell University", 42.4534492, -76.47350269999998, "noncollecting"],
    ["University of Chicago", 41.7886079, -87.59871329999999, "noncollecting"],
    ["Cornell University", 42.4534492, -76.47350269999998, "noncollecting"],
    ["Purdue University", 40.4237054, -86.92119459999998, "noncollecting"],
    ["Williams College", 42.7128038, -73.20302140000001, "noncollecting"],
    ["Michigan State University", 42.701848, -84.48217190000003, "noncollecting"],
    ["University of Waterloo", 43.4722854, -80.5448576, "noncollecting"],
    ["Temple University", 39.9811935, -75.15535119999998, "noncollecting"],
    ["University of Pittsburgh", 40.4443533, -79.96083499999997, "noncollecting"],
    ["Carnegie Mellon University", 40.4428081, -79.94301280000002, "noncollecting"],
    ["University of Connecticut", 41.8077414, -72.25398050000001, "noncollecting"],
    ["University of Washington", 47.65533509999999, -122.30351989999997, "noncollecting"],
    ["Penn State University", 40.7982133, -77.8599084, "noncollecting"],
    ["University of Illinois at Urbana-Champagne", 40.1019523, -88.22716149999997, "noncollecting"],
    ["Harvard University", 42.3770029, -71.11666009999999, "noncollecting"],
    ["University of Toronto Scarborough", 43.6628917, -79.39565640000001, "noncollecting"],
    ["University of Connecticut", 41.8077414, -72.25398050000001, "noncollecting"],
    ["University of Manitoba", 49.8075008, -97.13662590000001, "noncollecting"],
    ["Brooklyn College", 40.6314406, -73.95444880000002, "noncollecting"],
    ["New York University", 40.72951339999999, -73.99646089999999, "noncollecting"],
    ["University of California at Merced", 37.3648748, -120.42540020000001, "noncollecting"],
    ["University of Texas at Austin", 30.29128, -97.73858, "noncollecting"],
    ["Temple University", 39.9811935, -75.15535119999998, "noncollecting"]
  ];
      
      
  var infoWindow = new google.maps.InfoWindow(), marker, i;
    
  for( i = 0; i < markers.length; i++ ) {
      var position = new google.maps.LatLng(markers[i][1], markers[i][2]);
      bounds.extend(position);
      marker = new google.maps.Marker({
          position: position,
          map: map,
          title: markers[i][0],
          icon: "/web/icons/marker-" + markers[i][3] + ".png"
      });
          
      google.maps.event.addListener(marker, 'mouseover', (function(marker, i) {
          return function() {
              infoWindow.setContent('<div class="info_content">' + markers[i][0] + '</div>');
              infoWindow.open(map, marker);
          }
      })(marker, i));

      map.fitBounds(bounds);
  }

  var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function(event) {
      this.setCenter(new google.maps.LatLng(24.215527,-12.885834));
      this.setZoom(3);
      google.maps.event.removeListener(boundsListener);
  });
    
}  