function initMap() {
  var map;
  var bounds = new google.maps.LatLngBounds();
  var mapOptions = {
      mapTypeId: 'roadmap'
  };
                  
  map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
  map.setTilt(45);

  var geocoder = new google.maps.Geocoder();

  var universities = [
    ["Aalto University"],
    ["Abertay University"],
    ["Abraham Baldwin Agricultural College"],
    ["Academia Sinica"],
    ["Academic Medical Center"],
    ["Adam Mickiewicz University"],
    ["Adelphi University"],
    ["Aix Marseille University"],
    ["Albert Einstein College of Medicine"],
    ["Albright College"],
    ["Alexandru Ioan Cuza University"],
    ["Amherst College"],
    ["Appalachian State University"],
    ["Aristotle University of Thessaloniki"],
    ["Arizona State University"],
    ["Association Italian Teachers Method Feldenkrais (AIIMF)"],
    ["Australian Catholic University"],
    ["Babes-Bolyai University"],
    ["Bahcesehir University (Bahçeşehir Üniversitesi)"],
    ["Banja Luka University"],
    ["Bard College"],
    ["Barnard College, Columbia University"],
    ["Baruch College, CUNY"],
    ["Baylor College of Medicine"],
    ["Bilkent University"],
    ["Binghamton University"],
    ["Birkbeck, University of London"],
    ["Bordeaux INP - ENSEIRB-MATMECA"],
    ["Borough of Manhattan Community College"],
    ["Boston Children's Hospital"],
    ["Boston College"],
    ["Boston Medical Center"],
    ["Boston University"],
    ["Brigham Young University"],
    ["Brooklyn College, CUNY"],
    ["Brown University"],
    ["Bucknell University"],
    ["California Polytechnic State University, San Luis Obispo"],
    ["California State Polytechnic University, Pomona"],
    ["California State University, Fullerton"],
    ["California State University, Long Beach"],
    ["California State University, Northridge"],
    ["California State University, Sacramento"],
    ["California State University, San Bernardino"],
    ["California State University, Stanislaus"],
    ["Canisius College"],
    ["Capella University"],
    ["Cardiff University"],
    ["Carleton University"],
    ["Carlos Albizu University, San Juan"],
    ["Carnegie Mellon University"],
    ["Catholic University of Portugal (Universidade Catolica Portuguesa)"],
    ["Central European University"],
    ["Charité - University Medicine Berlin"],
    ["Chatham University"],
    ["Children's Hospital of Philadelphia (CHOP)"],
    ["Children’s Mercy Kansas City"],
    ["Christopher Newport University"],
    ["Cincinnati Children's Hospital Medical Center"],
    ["Clark University"],
    ["Claude Bernard University Lyon 1"],
    ["Clemson University"],
    ["Colby College"],
    ["College of Staten Island, CUNY"],
    ["College of the Holy Cross"],
    ["College of William & Mary"],
    ["Colorado College"],
    ["Colorado State University"],
    ["Columbia University"],
    ["Concordia University"],
    ["Connecticut College"],
    ["Copenhagen Business School"],
    ["Cornell University"],
    ["Curtin University"],
    ["Dalhousie University"],
    ["Dartmouth University"],
    ["DAV College"],
    ["Davidson College"],
    ["Deakin University"],
    ["DePaul University"],
    ["Duke University"],
    ["Duquesne University"],
    ["Earlham College"],
    ["East Carolina University"],
    ["Eastern Michigan University"],
    ["East Tennessee State University"],
    ["Edogawa University"],
    ["Emory University"],
    ["Farmingdale State College"],
    ["Federal University of Alagoas"],
    ["Federal University of Pará"],
    ["Federal University of Rio Grande do Sul (Universidade Federal do Rio Grande do Sul)"],
    ["Federal University of Rio Grande North"],
    ["Florida International University"],
    ["Florida State University"],
    ["Foundation CTIC"],
    ["Franklin and Marshall College"],
    ["Free University of Berlin (Freie Universität)"],
    ["Gallaudet University"],
    ["Gangneung-Wonju National University"],
    ["General Hospital of Mexico"],
    ["George Mason University"],
    ["Georgetown University"],
    ["George Washington University"],
    ["Georgia Institute of Technology"],
    ["Georgia State University"],
    ["Gettysburg College"],
    ["Goethe-University"],
    ["Goldsmiths University of London"],
    ["Graduate Center, CUNY"],
    ["Grand Valley State University"],
    ["Grinnell College"],
    ["Gustavus Adolphus College"],
    ["Hangzhou Normal University"],
    ["Harvard University"],
    ["Hofstra University"],
    ["Hong Kong University of Science and Technology"],
    ["Humboldt State University"],
    ["Humboldt-University of Berlin"],
    ["Hunter College, CUNY"],
    ["IE University"],
    ["Illinois Institute of Technology"],
    ["Indiana University"],
    ["Indiana University Kokomo"],
    ["Indian Institute of Science"],
    ["Indraprastha Institute of Information Technology Delhi"],
    ["Infantium"],
    ["INSERM"],
    ["Institute of Business Administration, Karachi"],
    ["Institute of Psychology, Chinese Academy of Sciences"],
    ["Interdisciplinary Center Herzliya"],
    ["IRCCS Stella Maris Foundation"],
    ["ISCTE - University Institute of Lisbon (IUL)"],
    ["Isfahan University of Medical Sciences"],
    ["Istanbul Technical University"],
    ["Italian Hospital of Buenos Aires"],
    ["ITESO University (Instituto Tecnologico y de Estudios Superiores de Occidente)"],
    ["Jagiellonian University"],
    ["Japan Advanced Institute of Science and Technology"],
    ["Johns Hopkins University"],
    ["Kansas State University"],
    ["Keele University"],
    ["King Khalid University"],
    ["Kingston University London"],
    ["Kobe University"],
    ["Koc University"],
    ["Kumamoto University"],
    ["Kutztown University of Pennsylvania"],
    ["Kyoto University"],
    ["Kyushu University"],
    ["Laboratoire de Sciences Cognitives et Psycholinguistique"],
    ["Lafayette College"],
    ["Lancaster University"],
    ["Lehigh University"],
    ["Lehman College, CUNY"],
    ["Leiden University"],
    ["Leipzig University (Universität Leipzig)"],
    ["Liverpool Hope University"],
    ["Lock Haven University"],
    ["London School of Economics and Political Science"],
    ["London South Bank University"],
    ["Louisiana State University"],
    ["Loyola University Chicago"],
    ["Ludwig Maximilian University of Munich"],
    ["Lynchburg College"],
    ["Macquarie University"],
    ["Marshall University"],
    ["Massachusetts Institute of Technology"],
    ["Max Planck Institute for Evolutionary Anthropology"],
    ["Max Planck Institute for Human Development"],
    ["Max Planck Institute for Psycholinguistics"],
    ["McGill University"],
    ["McMaster University"],
    ["Memorial University"],
    ["Mercy College"],
    ["Metropolitan State University"],
    ["Miami University"],
    ["Michigan State University"],
    ["Michigan Technological University"],
    ["Middlesex University"],
    ["Millersville University"],
    ["Montana State University"],
    ["Montclair State University"],
    ["Mount Saint Mary's University"],
    ["Narsee Monjee Institute of Management Studies"],
    ["National Autonomous University of Mexico"],
    ["National Institute of Astrophysics, Optics and Electronics"],
    ["National Institute of Child Health & Human Development NICHD"],
    ["National Institute of Mental Health (NUDZ/ NIMH)"],
    ["National Institute of Technology Durgapur"],
    ["National Institute of Technology Rourkela"],
    ["National Science Foundation (NSF)"],
    ["National Scientific and Technical Research Council (CONICET)"],
    ["National Taipei University of Technology"],
    ["National University of Córdoba"],
    ["National University of La Plata"],
    ["National University of Singapore"],
    ["Nationwide Children's Hospital"],
    ["Nencki Institute of Experimental Biology, Polish Academy of Sciences"],
    ["Newcastle University"],
    ["New College of Florida"],
    ["New School for Social Research"],
    ["New York State Institute for Basic Research in Developmental Disabilities"],
    ["New York University, School of Medicine"],
    ["New York University (NYU)"],
    ["Niagara University"],
    ["Niigata University"],
    ["Nile University of Nigeria"],
    ["North Dakota State University"],
    ["Northeastern University"],
    ["Northern Illinois University"],
    ["Northwestern University"],
    ["Norwegian University of Science and Technology"],
    ["Oberlin College"],
    ["Ohio State University"],
    ["Ohio State University, Lima"],
    ["Okinawa Institute of Science and Technology"],
    ["Oklahoma State University"],
    ["Old Dominion University"],
    ["Omsk State Pedagogical University"],
    ["Oregon Health and Science University"],
    ["Oregon State University"],
    ["Osaka University"],
    ["Oxford Brookes University"],
    ["Ozyegin University"],
    ["Pace University"],
    ["Pakistan Institute of Learning and Living"],
    ["Paris Descartes University"],
    ["Peking University First Hopsital"],
    ["Penn State University, Abington"],
    ["Penn State University, Brandywine"],
    ["Penn State University, University Park"],
    ["Penn State University, Worthington-Scranton"],
    ["Pomona College"],
    ["Pontifical Catholic University of Rio Grande do Sul (PUCRS)"],
    ["Pontificia Universidad Católica de Chile"],
    ["Princeton University"],
    ["Providence College"],
    ["Punjab University"],
    ["Purdue University"],
    ["Queen's University"],
    ["Queen's University, Belfast"],
    ["Queens College, CUNY"],
    ["Radboud University"],
    ["Ramapo College"],
    ["Randolph-Macon College"],
    ["Rhodes College"],
    ["Rice University"],
    ["Rikkyo University"],
    ["Rochester Institute of Technology"],
    ["Roosevelt University"],
    ["Rosalind Franklin University of Medicine and Science"],
    ["Rutgers University, Newark"],
    ["Rutgers University, New Brunswick"],
    ["Ryerson University"],
    ["Saarland University"],
    ["Sabanci University"],
    ["Sacred Heart University"],
    ["Saint Joseph's University"],
    ["Sakushin Gakuin University"],
    ["Sam Houston State University"],
    ["San Diego State University"],
    ["San Francisco State University"],
    ["San Jose State University"],
    ["Santa Clara University"],
    ["Sapienza University of Rome"],
    ["Seoul National University"],
    ["Seton Hall University"],
    ["Simon Fraser University"],
    ["Singapore University of Technology and Design"],
    ["Skidmore College"],
    ["Slippery Rock University"],
    ["Smith-Kettlewell Eye Research Institute"],
    ["Southern Illinois University"],
    ["Southern New Hampshire University"],
    ["Southwestern University"],
    ["St. Francis Xavier University"],
    ["St. John's University"],
    ["St. Lawrence University"],
    ["St. Mary's College of Maryland"],
    ["Stanford University"],
    ["State University of New York at Fredonia"],
    ["Stockholm University"],
    ["Sun Yat-Sen University"],
    ["Swarthmore"],
    ["Swinburne University of Technology"],
    ["SWPS University of Social Sciences and Humanities"],
    ["Syracuse University"],
    ["Teachers College, Columbia University"],
    ["Technion – Israel Institute of Technology"],
    ["Teesside University"],
    ["Tel Aviv University"],
    ["Temple University"],
    ["Texas A&M University"],
    ["Texas Christian University"],
    ["Texas Woman's University"],
    ["The Catholic University of America"],
    ["The University of British Columbia"],
    ["The University of Newcastle"],
    ["The University of Queensland"],
    ["The University of Scranton"],
    ["The University of Sydney"],
    ["The University of Texas at Arlington"],
    ["The University of Texas at Austin"],
    ["The University of Texas at Dallas"],
    ["The University of Western Australia"],
    ["Thompson Rivers University"],
    ["Tokyo Metropolitan University"],
    ["Toulouse University"],
    ["Trent University"],
    ["Trinity College"],
    ["Trinity College Dublin"],
    ["Tufts University"],
    ["Tulane University"],
    ["Ulm University"],
    ["Ulster University"],
    ["Universidade Federal do Paraná"],
    ["Université du Québec à Trois-Rivières"],
    ["Université du Québec en Outaouais"],
    ["Université Libre de Bruxelles"],
    ["Université Paul-Valéry Montpellier 3"],
    ["Universiti Putra Malaysia"],
    ["University at Buffalo"],
    ["University College London"],
    ["University Duesseldorf (Heinrich-Heine-Universität Düsseldorf)"],
    ["University Ibn Zohr (Université Ibn Zohr)"],
    ["University of Akron"],
    ["University of Alberta"],
    ["University of Algarve"],
    ["University of Angers"],
    ["University of Arizona"],
    ["University of Arkansas"],
    ["University of Arkansas at Little Rock"],
    ["University of Auckland"],
    ["University of Bath"],
    ["University of Brazil (Universidade de Brasilia)"],
    ["University of Cagliari"],
    ["University of Calgary"],
    ["University of California, Berkeley"],
    ["University of California, Davis"],
    ["University of California, Irvine"],
    ["University of California, Los Angeles"],
    ["University of California, Merced"],
    ["University of California, Riverside"],
    ["University of California, San Diego"],
    ["University of California, San Francisco"],
    ["University of California, Santa Barbara"],
    ["University of California, Santa Cruz"],
    ["University of Cambridge"],
    ["University of Campinas"],
    ["University of Canterbury"],
    ["University of Central Florida"],
    ["University of Central Lancashire"],
    ["University of Chicago"],
    ["University of Cleveland"],
    ["University of Cologne"],
    ["University of Colorado, Boulder"],
    ["University of Colorado, Colorado Springs"],
    ["University of Connecticut"],
    ["University of Cyprus"],
    ["University of Delaware"],
    ["University of Denver"],
    ["University of East Anglia"],
    ["University of East London"],
    ["University of Erlangen-Nuremberg"],
    ["University of Florida"],
    ["University of Franche-Comté (Université de Franche-Comté)"],
    ["University of Geneva"],
    ["University of Georgia"],
    ["University of Giessen"],
    ["University of Gothenburg"],
    ["University of Gottingen (Georg-August-Universität Göttingen)"],
    ["University of Granada (Universidad de Granada)"],
    ["University of Greifswald (Ernst-Moritz-Arndt-Universität Greifswald)"],
    ["University of Haifa"],
    ["University of Hamburg (Universität Hamburg)"],
    ["University of Hartford"],
    ["University of Hawaii - Manoa"],
    ["University of Houston"],
    ["University of Hull"],
    ["University of Illinois at Chicago"],
    ["University of Illinois Urbana-Champaign"],
    ["University of Innsbruck (Universität Innsbruck)"],
    ["University of Iowa"],
    ["University of Kansas"],
    ["University of Kent"],
    ["University of Kentucky"],
    ["University of Konstanz (Universität Konstanz)"],
    ["University of Leeds"],
    ["University of Lille"],
    ["University of Lincoln"],
    ["University of Lisbon"],
    ["University of Liverpool"],
    ["University of Los Andes (Universidad de los Andes)"],
    ["University of Louisiana, Lafayette"],
    ["University of Louisville"],
    ["University of Malaya"],
    ["University of Manchester"],
    ["University of Manitoba"],
    ["University of Maryland"],
    ["University of Massachusetts, Amherst"],
    ["University of Massachusetts, Boston"],
    ["University of Massachusetts, Dartmouth"],
    ["University of Memphis"],
    ["University of Miami"],
    ["University of Michigan"],
    ["University of Minnesota"],
    ["University of Missouri"],
    ["University of Missouri, Kansas City"],
    ["University of Missouri, St. Louis"],
    ["University of Mons"],
    ["University of Montana"],
    ["University of Montreal (Université de Montréal)"],
    ["University of Muenster (Münster)"],
    ["University of Nantes"],
    ["University of Nebraska, Lincoln"],
    ["University of Nevada, Las Vegas"],
    ["University of New Hampshire"],
    ["University of New Mexico"],
    ["University of New South Wales"],
    ["University of Nicosia"],
    ["University of North Carolina, Asheville"],
    ["University of North Carolina, Chapel Hill"],
    ["University of North Carolina, Greensboro"],
    ["University of North Carolina, School of Medicine"],
    ["University of North Carolina, Wilmington"],
    ["University of North Florida"],
    ["University of North Georgia"],
    ["University of Notre Dame"],
    ["University of Oklahoma"],
    ["University of Oregon"],
    ["University of Oslo"],
    ["University of Otago"],
    ["University of Ottawa"],
    ["University of Padua (Università di Padova)"],
    ["University of Paris Nanterre"],
    ["University of Pennsylvania"],
    ["University of Pittsburgh"],
    ["University of Poitiers (Université de Poitiers)"],
    ["University of Portsmouth"],
    ["University of Puget Sound"],
    ["University of Reading"],
    ["University of Redlands"],
    ["University of Regina"],
    ["University of Rennes (Université de Rennes)"],
    ["University of Rochester"],
    ["University of Salford"],
    ["University of São Paulo"],
    ["University of Sheffield"],
    ["University of South Brittany (Université de Bretagne Sud)"],
    ["University of South Carolina"],
    ["University of South Dakota"],
    ["University of Southern California"],
    ["University of South Florida"],
    ["University of St Andrews"],
    ["University of Stirling"],
    ["University of Surrey"],
    ["University of Sussex"],
    ["University of Tampere"],
    ["University of Tennessee"],
    ["University of the Balearic Islands"],
    ["University of the Basque Country"],
    ["University of the Incarnate Word"],
    ["University of the Pacific"],
    ["University of the Republic"],
    ["University of the Sciences"],
    ["University of the West of England"],
    ["University of Toledo"],
    ["University of Toronto"],
    ["University of Toulouse - Jean Jaurès (Université Toulouse - Jean Jaurès)"],
    ["University of Trento"],
    ["University of Trier (Universität Trier)"],
    ["University of Tuebingen (Tübingen)"],
    ["University of Utah"],
    ["University of Verona"],
    ["University of Virginia"],
    ["University of Warsaw"],
    ["University of Washington"],
    ["University of Waterloo"],
    ["University of Western Sydney"],
    ["University of Wisconsin, Green Bay"],
    ["University of Wisconsin, Madison"],
    ["University of Wisconsin, Milwaukee"],
    ["University of Wisconsin, Oshkosh"],
    ["University of Wisconsin, Whitewater"],
    ["University of Wuerzburg (University of Würzburg )"],
    ["University of York"],
    ["University of Zurich (Universität Zürich)"],
    ["University Paris 8"],
    ["University Saint Anne (Université Sainte-Anne)"],
    ["Uppsala University"],
    ["Utrecht University"],
    ["Vanderbilt University"],
    ["Vietnam Maritime University"],
    ["Villanova University"],
    ["Virginia Commonwealth University"],
    ["Virginia Military Institute"],
    ["Virginia Tech"],
    ["Vrije Universiteit Brussel"],
    ["Wabash College"],
    ["Wake Forest University"],
    ["Washington State University"],
    ["Washington University, St Louis"],
    ["Wayne State University"],
    ["Weill Cornell Medical College"],
    ["Wellesley College"],
    ["Wesleyan University"],
    ["Westmont College"],
    ["West Virginia University"],
    ["Wheaton College"],
    ["Whitman College"],
    ["Widener University"],
    ["Wilfrid Laurier University"],
    ["Williams College"],
    ["Worcester Polytechnic Institute"],
    ["Xidian University"],
    ["Yale University"],
    ["York University"] 
  ];

  var markers = [];
  var offset = 0;

  if (geocoder) {
    $.each(universities.slice(100, 110), function(index, value){
      setTimeout(function(){
        geocoder.geocode({ 'address': value[0] }, function (results, status) {
          if (status == google.maps.GeocoderStatus.OK) {
            value.push(results[0].geometry.location.lat());
            value.push(results[0].geometry.location.lng());
            console.log(universities);
          }
          else {
            console.log(google.maps.GeocoderStatus);
          }
        });
      }, 500 + offset);
      offset += 500;
    });  
  }

  setTimeout(function(){
    console.log(universities);
  }, 6000);
      
  var markers = [
    ["Aalto University", 60.1866693, 24.82768199999998],
    ["Abertay University", 56.4633316, -2.9739571999999725],
    ["Abraham Baldwin Agricultural College", 31.483078, -83.5301665],
    ["Academia Sinica", 25.0421852, 121.6145477],
    ["Academic Medical Center", 52.294629, 4.957973000000038],
    ["Adam Mickiewicz University", 52.4083974, 16.915402099999937],
    ["Adelphi University", 40.719728, -73.6517116],
    ["Aix Marseille University", 43.29362099999999, 5.358066000000008],
    ["Albert Einstein College of Medicine", 40.8521451, -73.84439380000003],
    ["Albright College", 40.3615027, -75.91062899999997],
    ["Alexandru Ioan Cuza University", 47.1739612, 27.572106299999973],
    ["Amherst College", 42.3709104, -72.5170028],
    ["Appalachian State University", 36.2134842, -81.68414480000001],
    ["Aristotle University of Thessaloniki", 40.6308283, 22.959222400000044],
    ["Arizona State University", 33.4242399, -111.92805269999997],
    ["Association Italian Teachers Method Feldenkrais (AIIMF)", 43.7677075, 11.2757787],
    ["Australian Catholic University", -27.3778982, 153.08932170000003],
    ["Babes-Bolyai University", 46.7677955, 23.59127620000004],
    ["Bahcesehir University (Bahçeşehir Üniversitesi)", 41.042072, 29.009015099999942],
    ["Banja Luka University", 44.7745476, 17.211192600000004],
    ["Bard College", 42.0203897, -73.91005439999998],
    ["Barnard College, Columbia University", 40.8090974, -73.96396319999997],
    ["Baruch College, CUNY", 40.7401991, -73.98337449999997],
    ["Baylor College of Medicine", 29.71052899999999, -95.39624099999997],
    ["Bilkent University", 39.8746147, 32.747596199999975],
    ["Binghamton University", 42.0893553, -75.96970490000001],
    ["Birkbeck, University of London", 51.521975, -0.13046199999996588],
    ["Bordeaux INP - ENSEIRB-MATMECA", 44.80663759999999, -0.6051667000000407],
    ["Borough of Manhattan Community College", 40.7187801, -74.01187770000001],
    ["Boston Children's Hospital", 42.3374646, -71.10532169999999],
    ["Boston College", 42.3355488, -71.16849450000001],
    ["Boston Medical Center", 42.3355155, -71.07285430000002],
    ["Boston University", 42.3504997, -71.1053991],
    ["Brigham Young University", 40.2518435, -111.64931560000002],
    ["Brooklyn College, CUNY", 40.6314406, -73.95444880000002],
    ["Brown University", 41.8267718, -71.40254820000001],
    ["Bucknell University", 40.9546869, -76.88355139999999],
    ["California Polytechnic State University, San Luis Obispo", 35.3050053, -120.66249419999997],
    ["California State Polytechnic University, Pomona", 34.0575651, -117.820741],
    ["California State University, Fullerton", 33.8829226, -117.88692609999998],
    ["California State University, Long Beach", 33.7838235, -118.11409040000001],
    ["California State University, Northridge", 34.24259070000001, -118.52771200000001],
    ["California State University, Sacramento", 38.5611436, -121.42404249999998],
    ["California State University, San Bernardino", 34.1821786, -117.32353239999998],
    ["California State University, Stanislaus", 37.5245713, -120.85688870000001],
    ["Canisius College", 42.9248338, -78.85148479999998],
    ["Capella University", 44.9761068, -93.26859869999998],
    ["Cardiff University", 51.48662710000001, -3.1788641000000553],
    ["Carleton University", 45.3875812, -75.69602020000002],
    ["Carlos Albizu University, San Juan", 18.4665523, -66.11402750000002],
    ["Carnegie Mellon University", 40.4428081, -79.94301280000002],
    ["Catholic University of Portugal (Universidade Catolica Portuguesa)", 41.1532817, -8.672126100000014],
    ["Central European University", 47.5005395, 19.04957999999999],
    ["Charité - University Medicine Berlin", 52.5264618, 13.376624499999934],
    ["Chatham University", 40.4482193, -79.9242625],
    ["Children's Hospital of Philadelphia (CHOP)", 39.9489145, -75.1939595],
    ["Children’s Mercy Kansas City", 39.0837665, -94.57746320000001],
    ["Christopher Newport University", 37.0646188, -76.49443839999998],
    ["Cincinnati Children's Hospital Medical Center", 39.1408554, -84.50197830000002],
    ["Clark University", 42.2523452, -71.82467029999998],
    ["Claude Bernard University Lyon 1", 45.7788727, 4.867961100000002],
    ["Clemson University", 34.6760942, -82.8364148],
    ["Colby College", 44.5638691, -69.66263620000001],
    ["College of Staten Island, CUNY", 40.6018152, -74.14849040000001],
    ["College of the Holy Cross", 42.2392391, -71.80796079999999],
    ["College of William & Mary", 37.271674, -76.71337799999998],
    ["Colorado College", 38.846594, -104.82439399999998],
    ["Colorado State University", 40.573436, -105.0865473],
    ["Columbia University", 40.8075355, -73.96257270000001],
    ["Concordia University", 45.5701912, -122.63688739999998],
    ["Connecticut College", 41.3786877, -72.10458690000002],
    ["Copenhagen Business School", 55.681611, 12.529678999999987],
    ["Cornell University", 42.4534492, -76.47350269999998],
    ["Curtin University", -32.0061951, 115.89441820000002],
    ["Dalhousie University", 44.63658119999999, -63.5916555],
    ["Dartmouth University", 43.7044406, -72.28869350000002],
    ["DAV College", 30.7523403, 76.7855614],
    ["Davidson College", 35.5017318, -80.84677929999998],
    ["Deakin University", -37.82052789999999, 144.9502334],
    ["DePaul University", 41.9256494, -87.654968],
    ["Duke University", 36.0014258, -78.9382286],
    ["Duquesne University", 40.4372949, -79.99017279999998],
    ["Earlham College", 39.8208853, -84.913052],
    ["East Carolina University", 35.6055108, -77.36456529999998],
    ["Eastern Michigan University", 42.2506803, -83.62408900000003],
    ["East Tennessee State University", 36.3025374, -82.37019329999998],
    ["Edogawa University", 35.8765371, 139.93873929999995],
    ["Emory University", 33.7925195, -84.32399889999999],
    ["Farmingdale State College", 40.752182, -73.42244599999998],
    ["Federal University of Alagoas", -9.554630300000001, -35.776021300000025],
    ["Federal University of Pará", -1.4743965, -48.453221799999994],
    ["Federal University of Rio Grande do Sul (Universidade Federal do Rio Grande do Sul)", -30.0338411, -51.21857019999999],
    ["Federal University of Rio Grande North", -5.8393707, -35.200772700000016],
    ["Florida International University", 25.756576, -80.37394899999998],
    ["Florida State University", 30.4418778, -84.2984889],
    ["Foundation CTIC", 43.521331,-5.609998],
    ["Franklin and Marshall College", 40.0475258, -76.31790160000003],
    ["Free University of Berlin (Freie Universität)", 52.4525264, 13.289678699999968],
    ["Gallaudet University", 38.908422, -76.9923875],
    ["Gangneung-Wonju National University", 37.7687678, 128.87014090000002]
  ];
      
  var infoWindow = new google.maps.InfoWindow(), marker, i;
    
  for( i = 0; i < markers.length; i++ ) {
      var position = new google.maps.LatLng(markers[i][1], markers[i][2]);
      bounds.extend(position);
      marker = new google.maps.Marker({
          position: position,
          map: map,
          title: markers[i][0]
      });
          
      google.maps.event.addListener(marker, 'mouseover', (function(marker, i) {
          return function() {
              infoWindow.setContent('<div class="info_content">' + markers[i][0] + '</div>');
              infoWindow.open(map, marker);
          }
      })(marker, i));

      map.fitBounds(bounds);
  }

  var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function(event) {
      this.setZoom(3);
      google.maps.event.removeListener(boundsListener);
  });
    
}  